#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Team4001.Droid.Resource", IsApplication=true)]

namespace Team4001.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int college1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int IMG_20150305_105500 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int IMG_20150305_105758 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int IMG_20150305_105810 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int IMG_20150305_111340 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int IMG_20150305_111349 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int IMG_20150305_115620 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int IMG_20150305_120103 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int IMG_20150305_120126 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int lifebuoy2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int newspaper20 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Rebound_BandW = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int RobotRender1 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int RobotRender2 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int RobotRender3 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int RobotRender4 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int RobotRender5 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int small164 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Team4001App = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Team4001WithRobot = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int tree58 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int tree83 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int tree93 = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f030000
			public const int Team4001Theme = 2130903040;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
